# Generated by Django 5.1.7 on 2026-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_multischedulepayment_multischedulepaymentassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
