# Generated by Django 5.1.7 on 2026-01-06 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_add_branch_manager_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="is_approved",
        ),
    ]
