# Generated by Django 5.1.7 on 2026-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_vault_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaulttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Cash Deposit"),
                    ("withdrawal", "Cash Withdrawal"),
                    ("transfer", "Branch Transfer"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("payment_collection", "Payment Collection"),
                    ("security_deposit", "Security Deposit"),
                    ("security_return", "Security Return"),
                    ("capital_injection", "Capital Injection"),
                    ("bank_withdrawal", "Bank Withdrawal"),
                    ("bank_charges", "Bank Charges"),
                    ("fund_deposit", "Fund Deposit"),
                    ("branch_transfer_out", "Branch Transfer (Out)"),
                    ("branch_transfer_in", "Branch Transfer (In)"),
                ],
                max_length=20,
            ),
        ),
    ]
