# Generated by Django 5.1.7 on 2026-04-15 16:32

from django.db import migrations


def add_other_expense_code(apps, schema_editor):
    """Add 'Other' expense code"""
    ExpenseCode = apps.get_model('expenses', 'ExpenseCode')
    
    # Check if 'Other' code already exists
    if not ExpenseCode.objects.filter(code='EXP-OTHER').exists():
        ExpenseCode.objects.create(
            code='EXP-OTHER',
            name='Other',
            description='Miscellaneous expenses that do not fit into other categories',
            is_active=True
        )


def remove_other_expense_code(apps, schema_editor):
    """Remove 'Other' expense code"""
    ExpenseCode = apps.get_model('expenses', 'ExpenseCode')
    ExpenseCode.objects.filter(code='EXP-OTHER').delete()


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_alter_vaulttransaction_types"),
    ]

    operations = [
        migrations.RunPython(add_other_expense_code, remove_other_expense_code),
    ]
