# Generated by Django 4.2.7 on 2025-12-06 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_clientverificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "max_members",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of members (leave blank for unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Loan officer responsible for this group",
                        limit_choices_to={"role": "loan_officer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Borrower Group",
                "verbose_name_plural": "Borrower Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this membership"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        limit_choices_to={"role": "borrower"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clients.borrowergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
                "ordering": ["-joined_date"],
                "unique_together": {("borrower", "group")},
            },
        ),
        migrations.CreateModel(
            name="OfficerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_groups",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of groups this officer can manage",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_clients",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum number of individual clients this officer can handle",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_accepting_assignments",
                    models.BooleanField(
                        default=True,
                        help_text="Is this officer accepting new assignments?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "officer",
                    models.OneToOneField(
                        limit_choices_to={"role": "loan_officer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officer_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Officer Assignment",
                "verbose_name_plural": "Officer Assignments",
            },
        ),
        migrations.RemoveField(
            model_name="clientverificationlog",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientverificationlog",
            name="performed_by",
        ),
        migrations.DeleteModel(
            name="ClientProfile",
        ),
        migrations.DeleteModel(
            name="ClientVerificationLog",
        ),
    ]
