# Generated by Django 5.1.7 on 2026-01-05 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_add_branch_and_audit_log"),
        ("clients", "0007_clientassignmentauditlog"),
    ]

    operations = []
