# Generated by Django 5.1.7 on 2026-01-06 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_approvalauditlog_clienttransferlog_and_more"),
    ]

    operations = [
        # This migration is intentionally empty - it's a placeholder for the orphaned 0012 migration
    ]
