# Generated by Django 5.1.7 on 2026-01-07 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_add_missing_foreign_keys"),
    ]

    operations = [
        # This migration is intentionally empty - it's a placeholder for the orphaned migration
    ]
