# Generated by Django 5.1.7 on 2026-01-13 21:16

from django.db import migrations, models


def safe_rename_index(apps, schema_editor):
    """Safely rename indexes if they exist"""
    from django.db import connection
    
    cursor = connection.cursor()
    table_name = 'clients_adminauditlog'
    
    # List of index renames to attempt
    index_renames = [
        ('clients_adm_admin_u_idx', 'clients_adm_admin_u_b673c4_idx'),
        ('clients_adm_action_idx', 'clients_adm_action_3aa84f_idx'),
        ('clients_adm_affected_idx', 'clients_adm_affecte_0f6520_idx'),
    ]
    
    # Get existing indexes
    cursor.execute(f"SHOW INDEXES FROM {table_name}")
    existing_indexes = {row[2] for row in cursor.fetchall()}
    
    # Only rename if old index exists
    for old_name, new_name in index_renames:
        if old_name in existing_indexes:
            try:
                cursor.execute(f"ALTER TABLE {table_name} RENAME INDEX {old_name} TO {new_name}")
            except Exception:
                pass  # Index might already be renamed


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0012_rename_clients_adm_admin_u_idx_clients_adm_admin_u_b673c4_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(safe_rename_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("branch_create", "Create Branch"),
                    ("branch_update", "Update Branch"),
                    ("branch_delete", "Delete Branch"),
                    ("officer_transfer", "Transfer Officer"),
                    ("officer_update", "Update Officer"),
                    ("group_transfer", "Transfer Group"),
                    ("client_transfer", "Transfer Client"),
                    ("loan_transfer", "Transfer Loan"),
                    ("loan_transfer_batch", "Transfer Multiple Loans"),
                    ("loan_approve", "Approve Loan"),
                    ("loan_reject", "Reject Loan"),
                    ("override_assignment", "Override Assignment"),
                    ("other", "Other"),
                ],
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
