# Generated by Django 4.2.7 on 2026-01-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_employment_business_fields"),
        ("accounts", "0003_alter_user_role"),
    ]

    operations = []
