# Generated by Django 5.1.7 on 2026-03-30 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_managers_user_district_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_officers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Has this loan officer been approved by a manager?",
            ),
        ),
    ]
