# Generated by Django 5.1.7 on 2026-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_officer_approval_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="guarantor1_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor1_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor1_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor1_nrc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor1_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_nrc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
