# Generated by Django 5.1.7 on 2026-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_guarantors_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="guarantor1_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="guarantor2_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
