# Generated by Django 4.2.30 on 2026-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_add_login_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="accounts_us_user_id_39428d_idx",
            old_name="accounts_ua_user_id_timest_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="accounts_us_action_d05323_idx",
            old_name="accounts_ua_action_timest_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="accounts_us_severit_357713_idx",
            old_name="accounts_ua_severit_timest_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="accounts_us_target__0b54e0_idx",
            old_name="accounts_ua_target__target__idx",
        ),
        migrations.RenameIndex(
            model_name="userloginsession",
            new_name="accounts_us_user_id_19dd07_idx",
            old_name="accounts_us_user_id_login_t_idx",
        ),
        migrations.RenameIndex(
            model_name="userloginsession",
            new_name="accounts_us_is_acti_7f6e38_idx",
            old_name="accounts_us_is_acti_login_t_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
