# Generated by Django 5.1.7 on 2026-01-08 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0003_remove_document_document_type_remove_document_loan_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who verified this document",
                limit_choices_to={"role__in": ["loan_officer", "manager", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_client_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientverification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who verified this client",
                limit_choices_to={"role__in": ["loan_officer", "manager", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
