# Generated by Django 5.1.7 on 2026-01-06 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_client_document_verification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="loan",
        ),
        migrations.RemoveField(
            model_name="document",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
        migrations.RenameIndex(
            model_name="clientdocument",
            new_name="documents_c_client__18ee01_idx",
            old_name="documents_c_client_status_idx",
        ),
        migrations.RenameIndex(
            model_name="clientdocument",
            new_name="documents_c_status_de9688_idx",
            old_name="documents_c_status_uploaded_idx",
        ),
        migrations.DeleteModel(
            name="DocumentType",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
