# Generated by Django 5.1.7 on 2026-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.CharField(
                blank=True, help_text="Branch where employee works", max_length=100
            ),
        ),
    ]
