# Generated by Django 5.1.7 on 2026-04-13 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_remove_employee_department_employee_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Base monthly salary amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payment_day",
            field=models.IntegerField(
                default=30,
                help_text="Day of month for salary payment (1-31, use 31 for last day)",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("mobile_money", "Mobile Money"),
                ],
                default="bank_transfer",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("processing", "Processing"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "total_expected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("due_date", models.DateField()),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="payroll.employee",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="payroll.payrollperiod",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payroll_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "employee__employee_id"],
                "unique_together": {("period", "employee")},
            },
        ),
    ]
