# Generated by Django 5.1.7 on 2026-01-06 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("loans", "0009_approvallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("transfer", "Transfer"),
                            ("override", "Override"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource affected (e.g., Branch, Officer, Client, Loan)",
                        max_length=50,
                    ),
                ),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("previous_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Audit Log",
                "verbose_name_plural": "Admin Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_53ed59_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="adminpanel__action__702fd5_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "-timestamp"],
                        name="adminpanel__resourc_6af6da_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="adminpanel__timesta_897571_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_audit_logs",
                        to="loans.loan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Audit Log",
                "verbose_name_plural": "Approval Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-timestamp"],
                        name="adminpanel__loan_id_94ba2f_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_3c5013_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_group_id", models.IntegerField(blank=True, null=True)),
                ("previous_group_name", models.CharField(blank=True, max_length=100)),
                ("new_group_id", models.IntegerField(blank=True, null=True)),
                ("new_group_name", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_transfer_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_transfers_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Transfer Log",
                "verbose_name_plural": "Client Transfer Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["client", "-timestamp"],
                        name="adminpanel__client__e2ff17_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_54d12d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("payment_received", "Payment Received"),
                            ("payment_recorded", "Payment Recorded"),
                            ("default_marked", "Default Marked"),
                            ("collection_attempt", "Collection Attempt"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_audit_logs",
                        to="loans.loan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Audit Log",
                "verbose_name_plural": "Collection Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-timestamp"],
                        name="adminpanel__loan_id_92ff7c_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_bfae78_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DisbursementAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursement_audit_logs",
                        to="loans.loan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursement_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disbursement Audit Log",
                "verbose_name_plural": "Disbursement Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-timestamp"],
                        name="adminpanel__loan_id_b8bdd0_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_6d4cdf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficerTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_branch", models.CharField(max_length=100)),
                ("new_branch", models.CharField(max_length=100)),
                (
                    "transferred_groups",
                    models.JSONField(
                        default=list, help_text="List of group IDs transferred"
                    ),
                ),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officer_transfers_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Officer Transfer Log",
                "verbose_name_plural": "Officer Transfer Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["officer", "-timestamp"],
                        name="adminpanel__officer_6e644a_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="adminpanel__perform_54cf61_idx",
                    ),
                ],
            },
        ),
    ]
