# Generated by Django 4.2.7 on 2025-10-30 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_term_months", models.IntegerField()),
                ("min_term_months", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=20, unique=True)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("term_months", models.IntegerField()),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("disbursed", "Disbursed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("disbursement_date", models.DateTimeField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("purpose", models.TextField()),
                ("collateral_description", models.TextField(blank=True)),
                (
                    "collateral_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_remaining",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("approval_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.loantype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
