# Generated by Django 4.2.7 on 2025-10-30 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="term_months",
            field=models.IntegerField(
                help_text="Loan term in months (1-12 months)",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Minimum term is 1 month"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, "Maximum term is 12 months"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="max_term_months",
            field=models.IntegerField(
                default=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Minimum term is 1 month"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, "Maximum term is 12 months"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="min_term_months",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Minimum term is 1 month"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, "Maximum term is 12 months"
                    ),
                ],
            ),
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_copy", "ID Copy"),
                            ("proof_of_income", "Proof of Income"),
                            ("bank_statement", "Bank Statement"),
                            ("employment_letter", "Employment Letter"),
                            ("business_license", "Business License"),
                            ("collateral_documents", "Collateral Documents"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(upload_to=loans.models.loan_document_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_documents",
                        to="loans.loan",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
