# Generated by Django 4.2.7 on 2025-12-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_alter_loan_term_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="upfront_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when upfront payment was made", null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="upfront_payment_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid upfront",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="upfront_payment_required",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="10% of principal amount",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="upfront_payment_verified",
            field=models.BooleanField(
                default=False, help_text="Has the upfront payment been verified?"
            ),
        ),
    ]
