# Generated by Django 4.2.7 on 2025-12-06 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0005_remove_loan_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily or weekly payment amount",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="weekly",
                help_text="Repayment frequency: daily or weekly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Loan term in days (for daily repayment)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Loan term in weeks (for weekly repayment)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="repayment_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="weekly",
                help_text="Repayment frequency for this loan type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=45.0,
                help_text="Interest rate (default 45%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="monthly_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: Use payment_amount instead",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="term_months",
            field=models.IntegerField(
                blank=True,
                help_text="DEPRECATED: Use term_days or term_weeks instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=45.0,
                help_text="Interest rate (default 45%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="max_term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum term in days (for daily loans)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="max_term_months",
            field=models.IntegerField(
                blank=True, help_text="DEPRECATED: No longer used", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="max_term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum term in weeks (for weekly loans)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="min_term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum term in days (for daily loans)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="min_term_months",
            field=models.IntegerField(
                blank=True, help_text="DEPRECATED: No longer used", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loantype",
            name="min_term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum term in weeks (for weekly loans)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
