# Generated by Django 4.2.7 on 2025-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_loan_upfront_payment_date_loan_upfront_payment_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily or weekly payment amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                default="weekly", help_text="daily or weekly", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Loan term in days (for daily repayment)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Loan term in weeks (for weekly repayment)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="max_term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum term in days (for daily loans)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="max_term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum term in weeks (for weekly loans)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="min_term_days",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum term in days (for daily loans)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="min_term_weeks",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum term in weeks (for weekly loans)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantype",
            name="repayment_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="weekly",
                max_length=10,
            ),
        ),
    ]
