# Generated by Django 4.2.7 on 2025-12-06 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_loan_payment_amount_loan_repayment_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="repayment_frequency",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="term_days",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="term_weeks",
        ),
        migrations.RemoveField(
            model_name="loantype",
            name="repayment_frequency",
        ),
    ]
