# Generated by Django 4.2.7 on 2025-12-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0006_loan_payment_amount_loan_repayment_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required deposit amount (10% of principal)",
                        max_digits=12,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually paid",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when deposit was paid", null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("check", "Check"),
                        ],
                        help_text="Method used for payment",
                        max_length=20,
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when deposit was verified",
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this deposit been verified by an admin?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this deposit"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt or transaction reference number",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.OneToOneField(
                        help_text="Loan associated with this security deposit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_deposit",
                        to="loans.loan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Manager who verified the deposit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Deposit",
                "verbose_name_plural": "Security Deposits",
                "ordering": ["-created_at"],
            },
        ),
    ]
