# Generated by Django 5.1.7 on 2026-01-05 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_add_approval_and_security_models"),
        ("loans", "0007_securitydeposit"),
    ]

    operations = []
