# Generated by Django 5.1.7 on 2026-01-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0008_merge_20260105_2049"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("security_deposit", "Security Deposit"),
                            ("security_topup", "Security Top-Up"),
                            ("security_return", "Security Return"),
                        ],
                        help_text="Type of approval",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "Approved"), ("reject", "Rejected")],
                        help_text="Approve or Reject",
                        max_length=10,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments about the approval/rejection",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        help_text="Branch where approval was made", max_length=100
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="loans.loan",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Log",
                "verbose_name_plural": "Approval Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-timestamp"],
                        name="loans_appro_loan_id_66e89b_idx",
                    ),
                    models.Index(
                        fields=["manager", "-timestamp"],
                        name="loans_appro_manager_570a79_idx",
                    ),
                    models.Index(
                        fields=["branch", "-timestamp"],
                        name="loans_appro_branch_2d9758_idx",
                    ),
                ],
            },
        ),
    ]
