# Generated by Django 5.1.7 on 2026-01-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0009_approvallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="manager_approval_required",
            field=models.BooleanField(
                default=False, help_text="Whether manager approval is needed"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="manager_approved_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when manager approved the loan", null=True
            ),
        ),
        migrations.CreateModel(
            name="ManagerLoanApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when loan was approved", null=True
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Optional comments about the approval"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.OneToOneField(
                        help_text="Loan being approved by manager",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_approval",
                        to="loans.loan",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved the loan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Loan Approval",
                "verbose_name_plural": "Manager Loan Approvals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-created_at"],
                        name="loans_manag_loan_id_ef9c57_idx",
                    ),
                    models.Index(
                        fields=["manager", "-created_at"],
                        name="loans_manag_manager_fafea6_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="loans_manag_status_66a1f6_idx",
                    ),
                ],
            },
        ),
    ]
