# Generated by Django 5.1.7 on 2026-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0011_alter_approvallog_approval_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvallog",
            name="approval_type",
            field=models.CharField(
                choices=[
                    ("security_deposit", "Security Deposit"),
                    ("security_topup", "Security Top-Up"),
                    ("security_return", "Security Return"),
                    ("loan_approval", "Loan Approval"),
                    ("loan_disbursement", "Loan Disbursement"),
                ],
                help_text="Type of approval",
                max_length=20,
            ),
        ),
    ]
