# Generated by Django 5.1.7 on 2026-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0016_vault"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily (40% interest)"),
                    ("weekly", "Weekly (45% interest)"),
                ],
                default="daily",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="securitytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("adjustment", "Balance Adjustment"),
                    ("return", "Security Return"),
                    ("carry_forward", "Carry Forward to Top-Up"),
                    ("withdrawal", "Security Withdrawal"),
                ],
                max_length=20,
            ),
        ),
    ]
