# Generated by Django 5.1.7 on 2026-03-30 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0017_add_repayment_frequency_to_loanapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="processing_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="processing_fee_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_processing_fees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="processing_fee_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="processing_fee_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="processing_fee_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_processing_fees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
