# Generated by Django 5.1.7 on 2026-04-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0013_rename_clients_adm_admin_u_idx_clients_adm_admin_u_b673c4_idx_and_more",
        ),
        ("loans", "0018_add_processing_fee_to_loanapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("adjustment", "Balance Adjustment"),
                    ("return", "Security Return"),
                    ("carry_forward", "Top-Ups"),
                    ("withdrawal", "Security Withdrawal"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BranchSavings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to="clients.branch",
                    ),
                ),
            ],
        ),
    ]
