# Generated by Django 5.1.7 on 2026-03-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0018_add_processing_fee_to_loanapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor1_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor1_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor1_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor1_nrc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor1_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor2_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor2_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor2_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor2_nrc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="guarantor2_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
