# Generated by Django 4.2.7 on 2025-12-08 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_borrowergroup_groupmembership_officerassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowergroup",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch this group belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="clients.branch"
            ),
        ),
        migrations.AddField(
            model_name="borrowergroup",
            name="payment_day",
            field=models.CharField(
                blank=True,
                help_text="Day of payment (e.g., Monday, Tuesday for weekly; or specific day number for daily)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="officerassignment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch where this loan officer is assigned",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_officers",
                to="clients.branch"
            ),
        ),
        migrations.AlterField(
            model_name="officerassignment",
            name="max_groups",
            field=models.IntegerField(
                default=15,
                help_text="Maximum number of groups this officer can manage (minimum 15)",
                validators=[django.core.validators.MinValueValidator(15)],
            ),
        ),
    ]
