# Generated by Django 4.2.7 on 2025-12-08 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_add_group_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowergroup",
            options={
                "ordering": ["name"],
                "permissions": [("can_create_group", "Can create borrower groups")],
                "verbose_name": "Borrower Group",
                "verbose_name_plural": "Borrower Groups",
            },
        ),
    ]
