# Generated by Django 4.2.7 on 2025-12-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0006_alter_borrowergroup_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAssignmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("reassign", "Reassign"),
                        ],
                        help_text="Type of assignment action",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for the assignment change",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this assignment change occurred",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The borrower client being assigned",
                        limit_choices_to={"role": "borrower"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The new loan officer (null if unassigning)",
                        limit_choices_to={"role": "loan_officer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="The user who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The previous loan officer (if reassigning)",
                        limit_choices_to={"role": "loan_officer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Assignment Audit Log",
                "verbose_name_plural": "Client Assignment Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["client", "-timestamp"],
                        name="clients_cli_client__fd4758_idx",
                    ),
                    models.Index(
                        fields=["new_officer", "-timestamp"],
                        name="clients_cli_new_off_32ffc1_idx",
                    ),
                ],
            },
        ),
    ]
