# Generated by Django 5.1.7 on 2026-01-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_add_branch_to_officerassignment"),
        ("loans", "0009_approvallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Approval action",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for action")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When action occurred"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of user", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Audit Log",
                "verbose_name_plural": "Approval Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ClientTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for transfer")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When transfer occurred"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Transfer Log",
                "verbose_name_plural": "Client Transfer Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CollectionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("partial", "Partial"),
                            ("missed", "Missed"),
                            ("default", "Default"),
                        ],
                        help_text="Collection action",
                        max_length=20,
                    ),
                ),
                (
                    "amount_expected",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected collection amount",
                        max_digits=12,
                    ),
                ),
                (
                    "amount_collected",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual collection amount",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When action occurred"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of user", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Audit Log",
                "verbose_name_plural": "Collection Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DisbursementAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("processed", "Processed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        help_text="Disbursement action",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount disbursed", max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When action occurred"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of user", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Disbursement Audit Log",
                "verbose_name_plural": "Disbursement Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoanApprovalQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When loan was submitted for approval",
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, help_text="When decision was made", null=True
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(
                        blank=True, help_text="Reason for approval/rejection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Approval Queue",
                "verbose_name_plural": "Loan Approval Queues",
                "ordering": ["-submitted_date"],
            },
        ),
        migrations.CreateModel(
            name="OfficerTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_branch",
                    models.CharField(help_text="Previous branch name", max_length=100),
                ),
                (
                    "new_branch",
                    models.CharField(help_text="New branch name", max_length=100),
                ),
                (
                    "transferred_groups",
                    models.JSONField(
                        default=list, help_text="List of group IDs transferred"
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for transfer")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When transfer occurred"
                    ),
                ),
            ],
            options={
                "verbose_name": "Officer Transfer Log",
                "verbose_name_plural": "Officer Transfer Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="borrowergroup",
            name="branch",
            field=models.CharField(
                blank=True,
                default="timezone.now",
                help_text="Branch this group belongs to",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="approvalauditlog",
            name="loan",
            field=models.ForeignKey(
                help_text="Loan being approved",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_audits",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="approvalauditlog",
            name="performed_by",
            field=models.ForeignKey(
                help_text="User who performed action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clienttransferlog",
            name="client",
            field=models.ForeignKey(
                help_text="Client being transferred",
                limit_choices_to={"role": "borrower"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clienttransferlog",
            name="new_group",
            field=models.ForeignKey(
                help_text="New group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_transfers",
                to="clients.borrowergroup",
            ),
        ),
        migrations.AddField(
            model_name="clienttransferlog",
            name="performed_by",
            field=models.ForeignKey(
                help_text="Admin who performed transfer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_client_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clienttransferlog",
            name="previous_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_transfers",
                to="clients.borrowergroup",
            ),
        ),
        migrations.AddField(
            model_name="collectionauditlog",
            name="loan",
            field=models.ForeignKey(
                help_text="Loan with collection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_audits",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="collectionauditlog",
            name="performed_by",
            field=models.ForeignKey(
                help_text="User who performed action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disbursementauditlog",
            name="loan",
            field=models.ForeignKey(
                help_text="Loan being disbursed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disbursement_audits",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="disbursementauditlog",
            name="performed_by",
            field=models.ForeignKey(
                help_text="User who performed action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursement_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapprovalqueue",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who made decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapprovalqueue",
            name="loan",
            field=models.OneToOneField(
                help_text="Loan awaiting approval",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_queue",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="officertransferlog",
            name="officer",
            field=models.ForeignKey(
                help_text="Officer being transferred",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officer_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officertransferlog",
            name="performed_by",
            field=models.ForeignKey(
                help_text="Admin who performed transfer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_officer_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="approvalauditlog",
            index=models.Index(
                fields=["loan", "-timestamp"], name="clients_app_loan_id_d1472f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalauditlog",
            index=models.Index(
                fields=["performed_by", "-timestamp"],
                name="clients_app_perform_02cdf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="clients_app_action_8ddaf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttransferlog",
            index=models.Index(
                fields=["client", "-timestamp"], name="clients_cli_client__16365c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttransferlog",
            index=models.Index(
                fields=["performed_by", "-timestamp"],
                name="clients_cli_perform_7a03dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionauditlog",
            index=models.Index(
                fields=["loan", "-timestamp"], name="clients_col_loan_id_1e7db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionauditlog",
            index=models.Index(
                fields=["performed_by", "-timestamp"],
                name="clients_col_perform_308664_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="clients_col_action_374d6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disbursementauditlog",
            index=models.Index(
                fields=["loan", "-timestamp"], name="clients_dis_loan_id_ff4ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disbursementauditlog",
            index=models.Index(
                fields=["performed_by", "-timestamp"],
                name="clients_dis_perform_3f81ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disbursementauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="clients_dis_action_aa8d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapprovalqueue",
            index=models.Index(
                fields=["status", "-submitted_date"],
                name="clients_loa_status_e427ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapprovalqueue",
            index=models.Index(
                fields=["decided_by", "-decision_date"],
                name="clients_loa_decided_784cad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="officertransferlog",
            index=models.Index(
                fields=["officer", "-timestamp"], name="clients_off_officer_89a431_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officertransferlog",
            index=models.Index(
                fields=["performed_by", "-timestamp"],
                name="clients_off_perform_e3732b_idx",
            ),
        ),
    ]
