# Generated by Django 5.1.7 on 2026-01-06 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_approvalauditlog_clienttransferlog_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE clients_approvalauditlog ADD COLUMN loan_id BIGINT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_approvalauditlog DROP COLUMN loan_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_approvalauditlog ADD COLUMN performed_by_id INT;",
            "ALTER TABLE clients_approvalauditlog DROP COLUMN performed_by_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_clienttransferlog ADD COLUMN client_id INT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_clienttransferlog DROP COLUMN client_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_clienttransferlog ADD COLUMN new_group_id BIGINT;",
            "ALTER TABLE clients_clienttransferlog DROP COLUMN new_group_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_clienttransferlog ADD COLUMN performed_by_id INT;",
            "ALTER TABLE clients_clienttransferlog DROP COLUMN performed_by_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_clienttransferlog ADD COLUMN previous_group_id BIGINT;",
            "ALTER TABLE clients_clienttransferlog DROP COLUMN previous_group_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_collectionauditlog ADD COLUMN loan_id BIGINT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_collectionauditlog DROP COLUMN loan_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_collectionauditlog ADD COLUMN performed_by_id INT;",
            "ALTER TABLE clients_collectionauditlog DROP COLUMN performed_by_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_disbursementauditlog ADD COLUMN loan_id BIGINT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_disbursementauditlog DROP COLUMN loan_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_disbursementauditlog ADD COLUMN performed_by_id INT;",
            "ALTER TABLE clients_disbursementauditlog DROP COLUMN performed_by_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_loanapprovalqueue ADD COLUMN decided_by_id INT;",
            "ALTER TABLE clients_loanapprovalqueue DROP COLUMN decided_by_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_loanapprovalqueue ADD COLUMN loan_id BIGINT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_loanapprovalqueue DROP COLUMN loan_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_officertransferlog ADD COLUMN officer_id INT NOT NULL DEFAULT 1;",
            "ALTER TABLE clients_officertransferlog DROP COLUMN officer_id;",
        ),
        migrations.RunSQL(
            "ALTER TABLE clients_officertransferlog ADD COLUMN performed_by_id INT;",
            "ALTER TABLE clients_officertransferlog DROP COLUMN performed_by_id;",
        ),
    ]
