# Generated by Django 5.1.7 on 2026-01-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_add_missing_foreign_keys"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_admin_u_b673c4_idx",
            old_name="clients_adm_admin_u_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_action_3aa84f_idx",
            old_name="clients_adm_action_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_affecte_0f6520_idx",
            old_name="clients_adm_affected_idx",
        ),
    ]
