# Generated by Django 5.1.7 on 2026-01-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_add_missing_foreign_keys"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_admin_u_b673c4_idx",
            old_name="clients_adm_admin_u_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_action_3aa84f_idx",
            old_name="clients_adm_action_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_affecte_0f6520_idx",
            old_name="clients_adm_affected_idx",
        ),
        # First, remove the old CharField columns
        migrations.RemoveField(
            model_name='borrowergroup',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='officerassignment',
            name='branch',
        ),
        # Then add the new ForeignKey fields
        migrations.AddField(
            model_name='borrowergroup',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                help_text="Branch this group belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="clients.branch",
            ),
        ),
        migrations.AddField(
            model_name='officerassignment',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                help_text="Branch where this loan officer is assigned",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_officers",
                to="clients.branch",
            ),
        ),
    ]
