# Generated by Django 5.1.7 on 2026-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0012_rename_clients_adm_admin_u_idx_clients_adm_admin_u_b673c4_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_admin_u_b673c4_idx",
            old_name="clients_adm_admin_u_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_action_3aa84f_idx",
            old_name="clients_adm_action_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="clients_adm_affecte_0f6520_idx",
            old_name="clients_adm_affected_idx",
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("branch_create", "Create Branch"),
                    ("branch_update", "Update Branch"),
                    ("branch_delete", "Delete Branch"),
                    ("officer_transfer", "Transfer Officer"),
                    ("officer_update", "Update Officer"),
                    ("group_transfer", "Transfer Group"),
                    ("client_transfer", "Transfer Client"),
                    ("loan_transfer", "Transfer Loan"),
                    ("loan_transfer_batch", "Transfer Multiple Loans"),
                    ("loan_approve", "Approve Loan"),
                    ("loan_reject", "Reject Loan"),
                    ("override_assignment", "Override Assignment"),
                    ("other", "Other"),
                ],
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
