# Generated by Django 4.2.7 on 2025-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('payment_received', 'Payment Received'), ('payment_rejected', 'Payment Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('document_required', 'Document Required'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected')], max_length=50, unique=True),
        ),
    ]
