# Generated by Django 5.1.3 on 2026-01-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationtemplate_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App Notification"),
                ],
                default="in_app",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="scheduled_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notificationtemplate",
            ),
        ),
    ]
