# Generated by Django 5.0 on 2025-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('loan_officer', 'Loan Officer'), ('borrower', 'Borrower')], default='borrower', max_length=20),
        ),
    ]
