# Generated by Django 5.1.3 on 2026-01-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_residential_address"),
        ("accounts", "0004_merge_20260113_2254"),
    ]

    operations = []
